[2024-11-08T22:04:15.014+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-08T22:04:15.042+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-08T22:04:14.378727+00:00 [queued]>
[2024-11-08T22:04:15.050+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-08T22:04:14.378727+00:00 [queued]>
[2024-11-08T22:04:15.052+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-08T22:04:15.063+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_mongo> on 2024-11-08 22:04:14.378727+00:00
[2024-11-08T22:04:15.067+0000] {standard_task_runner.py:64} INFO - Started process 1376 to run task
[2024-11-08T22:04:15.070+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_mongo', 'manual__2024-11-08T22:04:14.378727+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmpf8tlc1u4']
[2024-11-08T22:04:15.072+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask fetch_data_from_mongo
[2024-11-08T22:04:15.119+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-08T22:04:14.378727+00:00 [running]> on host ea2549ac0aa6
[2024-11-08T22:04:15.196+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T22:04:14.378727+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-08T22:04:14.378727+00:00'
[2024-11-08T22:04:15.197+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-08T22:04:15.206+0000] {base.py:84} INFO - Using connection ID 'mongo_default' for task execution.
[2024-11-08T22:04:15.207+0000] {logging_mixin.py:188} INFO - Error connecting to MongoDB: Bad database name "/***:***@journals"
[2024-11-08T22:04:15.208+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-08T22:04:15.208+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-08T22:04:15.215+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_mongo, run_id=manual__2024-11-08T22:04:14.378727+00:00, execution_date=20241108T220414, start_date=20241108T220415, end_date=20241108T220415
[2024-11-08T22:04:15.243+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-08T22:04:15.264+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-08T22:04:15.267+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
