[2024-11-08T21:42:16.190+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-08T21:42:16.218+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-08T21:42:15.528468+00:00 [queued]>
[2024-11-08T21:42:16.227+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-08T21:42:15.528468+00:00 [queued]>
[2024-11-08T21:42:16.228+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-08T21:42:16.257+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_mongo> on 2024-11-08 21:42:15.528468+00:00
[2024-11-08T21:42:16.260+0000] {standard_task_runner.py:64} INFO - Started process 423 to run task
[2024-11-08T21:42:16.265+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_mongo', 'manual__2024-11-08T21:42:15.528468+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmpcgye8pwv']
[2024-11-08T21:42:16.268+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask fetch_data_from_mongo
[2024-11-08T21:42:16.315+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_mongo manual__2024-11-08T21:42:15.528468+00:00 [running]> on host ea2549ac0aa6
[2024-11-08T21:42:16.389+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T21:42:15.528468+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-08T21:42:15.528468+00:00'
[2024-11-08T21:42:16.390+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-08T21:42:16.400+0000] {base.py:84} INFO - Using connection ID 'mongo_default' for task execution.
[2024-11-08T21:42:46.743+0000] {logging_mixin.py:188} INFO - Error connecting to MongoDB: journals.yg9j2.mongodb.net:27017: [Errno -5] No address associated with hostname (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 672e85b8126610cc23ced9f1, topology_type: Unknown, servers: [<ServerDescription ('journals.yg9j2.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('journals.yg9j2.mongodb.net:27017: [Errno -5] No address associated with hostname (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2024-11-08T21:42:46.745+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-08T21:42:46.746+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-08T21:42:46.756+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_mongo, run_id=manual__2024-11-08T21:42:15.528468+00:00, execution_date=20241108T214215, start_date=20241108T214216, end_date=20241108T214246
[2024-11-08T21:42:46.807+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-08T21:42:46.830+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-08T21:42:46.833+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
